- CODE_OF_CONDUCT.md
> CODE_OF CODUCT

- Cheat Sheets/ML with Python.md
- Cheat Sheets/Python Learning.md
Started with adding the best resources to learn ML and will keep adding different cheat sheets related to same domain.
> Adding Cheat_Sheets

- Extract_Text_from_PDF_using_Python/Text_to_pdf.py.ipynb
- Extract_Text_from_PDF_using_Python/readme.md
Uploaded Extract Text from PDF using Python
Updated README.md
Issue #25
> Added Extract Text from PDF using Python

- Email Classifier/Emails_spam_or_not.ipynb
- Email Classifier/README.md
Fixes #103 
The goal is to predict email is spam or not.
MODELS USED
-  Decission Tree
-  Naive Bayes
> Email Classifier

- Meteorite Landing Data Analysis/Meteorite.ipynb
- Meteorite Landing Data Analysis/README.md
This project's aim is to provide a data analysis of meteorite landings on the earth over the course of hundreds of years.
LGM-SoC'21 Participant
Closes - #130
> Meteorite landing

- Fake_News_Detection/.ipynb_checkpoints/Fake_News_Detection-checkpoint.ipynb
- Fake_News_Detection/Fake_News_Detection.ipynb
- Fake_News_Detection/README.md
- README.md
This is a Fake News Detection Project developed in python as per issue #202  that was assigned to me under GSSoC'22. 
This project is a Fake News Detection system using NLP and Logistic regression to make the prediction, on whether the news is fake or not.
Libraries used :
- Numpy
- Pandas
- Matplotlib
- Seaborn
- re
- nltk
- sklearn
Steps being followed :
- Import libraries
- Load the dataset
-  Data Processing
- Stemming
- Convert text to numerical data
- Splitting data into test and train
- Logistic Regression model
- Evaluate
> Fake News Detection in python

- R language/Basic/Assignment_operator.R
- R language/Basic/Conditional.R
- R language/Basic/Loops.R
- R language/Basic/Operators.R
- R language/Basic/R-objects.R
- R language/Basic/first_program.R
- R language/Basic/function.R
- R language/README.md
@Niketkumardheeryan  @Rutikab12 @pratishthaa Completed on issue 245 please check it out and if there is some correction please let me know.
It fixes https://github.com/Niketkumardheeryan/ML-CaPsule/issues/245
> R language

- Tensorflow.js Demo/README.md
- Tensorflow.js Demo/demo.css
- Tensorflow.js Demo/demo.html
- Tensorflow.js Demo/demo.js
> Basic Demo of Tensorflow.js Added

- Chatbot Using RASA/RASA_Chatbot.ipynb
- Chatbot Using RASA/README.md
- Chatbot Using RASA/config.yml
- Chatbot Using RASA/domain.yml
- Chatbot Using RASA/nlu.md
- Chatbot Using RASA/stories.md
> RASA Chatbot added

- Cheat Sheets/Matplotlib.md
- Cheat Sheets/Numpy.md
- Cheat Sheets/Pandas.md
- Cheat Sheets/seaborn.md
issue- #445 
I've added some cheatsheets on Numpy, Pandas, Matplotlib, and Seaborn.
> updated cheatsheets

- PyScript Tutorial/README.md
- PyScript Tutorial/index.html
- PyScript Tutorial/sort.py
- PyScript Tutorial/style.css
Related Issue: #475
Site Link: https://mlcapsule-pyscript-tutorial.netlify.app/
> Pyscript Tutorial added

- Malicious Url Detection/MaliciousUrlDetection.ipynb
- Malicious Url Detection/readme.md
Issue Number #496 
Objective - In this project, I have built a primary binary classifier that would help classify the URLs as malicious or benign.
Result - I have used two models for my classification.
- Decision Trees
- Random Forest
- 
The accuracies of using these two models are as follows
> Malicious URL Detection using Machine Learning

- Activation Functions.md
> Activation Function Documentation added

- NumPy - Basics/NumPy - Basics.ipynb
I'm a GsSOC contributor. Please count this as my contribution @Niketkumardheeryan
> Added more functions

- Text Summarization Model/Model/text_summary.ipynb
- Text Summarization Model/README.md
**ISSUE**:- #586 
This text summarization model uses the **Natural Language Toolkit (NLTK)** library for text processing and **Networkx** for implementing **TextRank**.
**Features**:
- **Automatic** **Summarization**: The algorithm automatically generates summaries for input text by identifying important sentences using graph-based ranking techniques.
- **Customizable**: Users can adjust parameters such as the similarity threshold to control the length and quality of the summary.
- **Natural** **Language** **Processing**: The project utilizes natural language processing techniques such as tokenization, stop word removal, and cosine similarity computation.
- **Python** **Implementation**: Implemented in Python using libraries such as NLTK, NumPy, and NetworkX.
> Added Text Summarization Model.

- Movie Genre Classification/Readme.md
Please review and merge this PR @Niketkumardheeryan .
Also, please assign level 1/2/3 to the issue so that this can count towards my contribution as part of GSSoC'24. Thank you
> Added Movie Genre Classification [Issue No. #566]

- .github/ISSUES_TEMPLATE/bug_report.md
- .github/ISSUES_TEMPLATE/documentation.md
- .github/ISSUES_TEMPLATE/feature_request.md
> Added issues templates

- PulseLangX/Dockerfile
- PulseLangX/README.md
- PulseLangX/pages/translate_💤️.py
- PulseLangX/requirements.txt
- PulseLangX/welcome_👋️.py
I solved Issue #711 by impelment the project code for translating between various global dialects
> Added PulseLangX project successfully

- Feature-Engineering/Feature_Engineering.ipynb
- Feature-Engineering/Readme.md
Feature Engineering 
Closes: #731 
I have added `Feature_Engineering.ipynb` in the repository. 
What sort of change have you made:
> Added Feature Engineering

- Learning Rules In ANN/Learning-Rules.md
- Learning Rules In ANN/learning_rules.ipynb
Implementation of different learning rules in Neural Network, like Hebbian and Adeline from scratch.
Resolve Issue #979.
> Added learning rules in ANN

- NLP-Project/NLP_Project.ipynb
- NLP-Project/README.md
NLP Project is added which performs various processes of the Natural Language Processing (NLP) on English Corpus as well as Hindi Corpus. The code is easy to read and explains each process briefly. I have also uploaded the Hindi dataset taken from Kaggle, which i have used in the code.
GitHub Username: Apoorva57
Email ID: apoorvas2075@gmail.com
Identify yourself: GSSoC'24 Participant
Closes: #1033 issue and follows the rules of #5 #214 
Kindly review my PR and thank you for this opportunity to contribute
> NLP Project added

- Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms.ipynb
- Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/readme.md
- Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/requirement.txt
> Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms added

- railway_person_detection/.gitignore
- railway_person_detection/README.md
- railway_person_detection/railway_person_detection.py
- railway_person_detection/requirements.txt
> railway_person_detection added

- Digital Image Tampering Detection/Readme.md
- Digital Image Tampering Detection/requirements.txt
This pull request adds documentation and dependencies for the Digital Image Tampering Detection project using the CASIA dataset. The most important changes include the addition of a comprehensive README file and the required dependencies listed in the `requirements.txt` file.
Model Building and prediction code: 
* `Digital Image Tampering Detection/notebook.ipynb`: Added the complete project notebook, including ELA and CNN model building and testing and mask analysis.
Documentation:
* [`Digital Image Tampering Detection/Readme.md`](diffhunk://#diff-c4ab8617c2f7c7e00f218ed2e9f3bac136d2fbedc8017a0e4a8625a308224917R1-R72): Added an extensive overview of the project, dataset information, installation instructions, usage guidelines, approach details, and usability information.
Dependency …
> added project Digital Image Tampering Detection (Issue #1114)

- Basics of the Python/Best Practices Questions and Solutions/Best Python programs.txt
Issue number: #1087 
This pull request adds Python programs from problem 83 to 114. These programs cover a wide range of fundamental concepts and programming techniques, including:
1. Variable Length Arguments: Demonstrating the use of positional (*args) and keyword (**kwargs) arguments in Python functions.
2. Number Manipulations: Programs for reversing a number, checking for palindromes, and computing Armstrong numbers.
3. Patterns and Sequences: Constructing patterns using loops, including alphabetical and numerical sequences.
4. List and Tuple Operations: Various programs performing operations like sorting, counting occurrences, swapping cases, and finding common elements between tuples.
5. String Manipulations: Extracting digits from strings, counting occurrences of substrings, …
> Update Best Python programs.txt
